[build]
  command="npm run build"
  publish="https://github.com/BuildForSDGCohort2/chow-frontend/tree/develop/chow/build"
  base="https://github.com/BuildForSDGCohort2/chow-frontend/tree/develop/chow"
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200